# Default E2E profile

auth:
  email: "admin@example.com"
  password: "admin"

testrail:
  run_id: ""
  url: ""
  user: ""
  password: ""

image_registry:
  url: "https://index.docker.io/v1"
  repository: ""
  username: ""
  password: ""

model_registry:
  type: "hugging-face"
  url: "https://huggingface.co"
  credentials: ""

ssh_nodes: []

kubernetes:
  kubeconfig: ""
  router_access_mode: "LoadBalancer"

engine:
  name: "vllm"
  version: "v0.8.5"

model:
  name: "test-model"
  version: "1.0"
  file: "model.safetensors"
  task: "text-generation"

model_cache:
  host_path: "/data/models"
  nfs_server: ""
  nfs_path: ""
  pvc_storage_class: ""
